sudo: false
language: node_js
node_js:
  - 'stable'
  - '0.12'
  - '0.10'
before_script:
  - npm install -g gulp
  - gulp lint
after_success: npm run coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kempdogg@gmail.com
